export type ShowtimeEvent = {
  id: string
  name: string
  category: string
  mainCategory: 'Tech' | 'Non-Tech' | 'Sports' | 'Cultural Fest'
  date: string
  timeSlot: string
  endTime: string
  venue: string
  fillingFast: boolean
  maxParticipants: number
  day: 'THU' | 'FRI' | 'SAT'
  dayLabel: string
}

export const FESTIVAL_DATES = [
  { key: '2026-05-14', label: 'THU 14 MAY', short: 'THU', day: 14 },
  { key: '2026-05-15', label: 'FRI 15 MAY', short: 'FRI', day: 15 },
  { key: '2026-05-16', label: 'SAT 16 MAY', short: 'SAT', day: 16 },
]

export const showtimeEvents: ShowtimeEvent[] = [
  {
    id: 'debugging-thu',
    name: 'Debugging Challenge',
    category: 'Technical',
    mainCategory: 'Tech',
    date: '2026-05-14',
    timeSlot: '09:00 AM',
    endTime: '11:00 AM',
    venue: 'Lab Block A - Room 101',
    fillingFast: true,
    maxParticipants: 40,
    day: 'THU',
    dayLabel: 'THU 14 MAY',
  },
  {
    id: 'blind-coding-thu',
    name: 'Blind Coding',
    category: 'Technical',
    mainCategory: 'Tech',
    date: '2026-05-14',
    timeSlot: '11:30 AM',
    endTime: '01:00 PM',
    venue: 'Lab Block A - Room 102',
    fillingFast: false,
    maxParticipants: 30,
    day: 'THU',
    dayLabel: 'THU 14 MAY',
  },
  {
    id: 'solo-dance-thu',
    name: 'Solo Dance',
    category: 'Dance',
    mainCategory: 'Non-Tech',
    date: '2026-05-14',
    timeSlot: '10:00 AM',
    endTime: '01:00 PM',
    venue: 'Main Auditorium',
    fillingFast: true,
    maxParticipants: 60,
    day: 'THU',
    dayLabel: 'THU 14 MAY',
  },
  {
    id: 'solo-singing-thu',
    name: 'Solo Singing',
    category: 'Music',
    mainCategory: 'Non-Tech',
    date: '2026-05-14',
    timeSlot: '02:00 PM',
    endTime: '04:30 PM',
    venue: 'Main Auditorium',
    fillingFast: false,
    maxParticipants: 50,
    day: 'THU',
    dayLabel: 'THU 14 MAY',
  },
  {
    id: 'photography-thu',
    name: 'Photography',
    category: 'Fun',
    mainCategory: 'Non-Tech',
    date: '2026-05-14',
    timeSlot: '09:00 AM',
    endTime: '12:00 PM',
    venue: 'Campus Grounds',
    fillingFast: true,
    maxParticipants: 35,
    day: 'THU',
    dayLabel: 'THU 14 MAY',
  },
  {
    id: 'kho-kho-boys-thu',
    name: 'Kho Kho (Boys)',
    category: 'Sports',
    mainCategory: 'Sports',
    date: '2026-05-14',
    timeSlot: '08:00 AM',
    endTime: '12:00 PM',
    venue: 'Sports Ground - Field 1',
    fillingFast: false,
    maxParticipants: 24,
    day: 'THU',
    dayLabel: 'THU 14 MAY',
  },
  {
    id: 'chess-boys-thu',
    name: 'Chess',
    category: 'Indoor Sports',
    mainCategory: 'Sports',
    date: '2026-05-14',
    timeSlot: '09:00 AM',
    endTime: '01:00 PM',
    venue: 'Conference Hall - Room 201',
    fillingFast: false,
    maxParticipants: 32,
    day: 'THU',
    dayLabel: 'THU 14 MAY',
  },
  {
    id: 'dumb-charades-thu',
    name: 'Dumb Charades',
    category: 'Fun',
    mainCategory: 'Non-Tech',
    date: '2026-05-14',
    timeSlot: '03:00 PM',
    endTime: '05:00 PM',
    venue: 'Seminar Hall B',
    fillingFast: true,
    maxParticipants: 40,
    day: 'THU',
    dayLabel: 'THU 14 MAY',
  },
  {
    id: 'sketching-thu',
    name: 'Sketching',
    category: 'Fun',
    mainCategory: 'Non-Tech',
    date: '2026-05-14',
    timeSlot: '02:00 PM',
    endTime: '04:00 PM',
    venue: 'Art Room - Block C',
    fillingFast: false,
    maxParticipants: 45,
    day: 'THU',
    dayLabel: 'THU 14 MAY',
  },
  {
    id: 'stand-up-thu',
    name: 'Stand-Up Comedy',
    category: 'Speaking',
    mainCategory: 'Non-Tech',
    date: '2026-05-14',
    timeSlot: '05:00 PM',
    endTime: '07:00 PM',
    venue: 'Open Air Theatre',
    fillingFast: true,
    maxParticipants: 20,
    day: 'THU',
    dayLabel: 'THU 14 MAY',
  },
  {
    id: 'competitive-coding-fri',
    name: 'Competitive Coding',
    category: 'Technical',
    mainCategory: 'Tech',
    date: '2026-05-15',
    timeSlot: '09:00 AM',
    endTime: '12:00 PM',
    venue: 'Lab Block B - Room 201',
    fillingFast: true,
    maxParticipants: 50,
    day: 'FRI',
    dayLabel: 'FRI 15 MAY',
  },
  {
    id: 'paper-presentation-fri',
    name: 'Paper Presentation',
    category: 'Technical',
    mainCategory: 'Tech',
    date: '2026-05-15',
    timeSlot: '10:00 AM',
    endTime: '01:00 PM',
    venue: 'Seminar Hall A',
    fillingFast: false,
    maxParticipants: 30,
    day: 'FRI',
    dayLabel: 'FRI 15 MAY',
  },
  {
    id: 'group-dance-fri',
    name: 'Group Dance',
    category: 'Dance',
    mainCategory: 'Non-Tech',
    date: '2026-05-15',
    timeSlot: '10:00 AM',
    endTime: '01:00 PM',
    venue: 'Main Auditorium',
    fillingFast: true,
    maxParticipants: 30,
    day: 'FRI',
    dayLabel: 'FRI 15 MAY',
  },
  {
    id: 'battle-of-bands-fri',
    name: 'Battle of Bands',
    category: 'Music',
    mainCategory: 'Non-Tech',
    date: '2026-05-15',
    timeSlot: '03:00 PM',
    endTime: '06:00 PM',
    venue: 'Main Auditorium',
    fillingFast: true,
    maxParticipants: 15,
    day: 'FRI',
    dayLabel: 'FRI 15 MAY',
  },
  {
    id: 'debate-fri',
    name: 'Debate',
    category: 'Fun',
    mainCategory: 'Non-Tech',
    date: '2026-05-15',
    timeSlot: '11:00 AM',
    endTime: '01:00 PM',
    venue: 'Seminar Hall B',
    fillingFast: false,
    maxParticipants: 40,
    day: 'FRI',
    dayLabel: 'FRI 15 MAY',
  },
  {
    id: 'kabaddi-boys-fri',
    name: 'Kabaddi (Boys)',
    category: 'Sports',
    mainCategory: 'Sports',
    date: '2026-05-15',
    timeSlot: '08:00 AM',
    endTime: '12:00 PM',
    venue: 'Sports Ground - Field 2',
    fillingFast: false,
    maxParticipants: 24,
    day: 'FRI',
    dayLabel: 'FRI 15 MAY',
  },
  {
    id: 'badminton-boys-fri',
    name: 'Badminton (Boys)',
    category: 'Indoor Sports',
    mainCategory: 'Sports',
    date: '2026-05-15',
    timeSlot: '09:00 AM',
    endTime: '05:00 PM',
    venue: 'Indoor Stadium',
    fillingFast: true,
    maxParticipants: 32,
    day: 'FRI',
    dayLabel: 'FRI 15 MAY',
  },
  {
    id: 'rangoli-fri',
    name: 'Rangoli',
    category: 'Fun',
    mainCategory: 'Non-Tech',
    date: '2026-05-15',
    timeSlot: '09:00 AM',
    endTime: '11:00 AM',
    venue: 'Foyer - Block A',
    fillingFast: false,
    maxParticipants: 40,
    day: 'FRI',
    dayLabel: 'FRI 15 MAY',
  },
  {
    id: 'ai-art-fri',
    name: 'AI Art Battle',
    category: 'Technical',
    mainCategory: 'Tech',
    date: '2026-05-15',
    timeSlot: '02:00 PM',
    endTime: '04:00 PM',
    venue: 'Lab Block A - Room 103',
    fillingFast: true,
    maxParticipants: 25,
    day: 'FRI',
    dayLabel: 'FRI 15 MAY',
  },
  {
    id: 'skit-fri',
    name: 'Skit (Social Awareness)',
    category: 'Theatre',
    mainCategory: 'Non-Tech',
    date: '2026-05-15',
    timeSlot: '04:00 PM',
    endTime: '06:00 PM',
    venue: 'Open Air Theatre',
    fillingFast: false,
    maxParticipants: 30,
    day: 'FRI',
    dayLabel: 'FRI 15 MAY',
  },
  {
    id: 'hack-scenario-sat',
    name: 'Mini Hack Scenario',
    category: 'Technical',
    mainCategory: 'Tech',
    date: '2026-05-16',
    timeSlot: '09:00 AM',
    endTime: '01:00 PM',
    venue: 'Lab Block B - Room 202',
    fillingFast: true,
    maxParticipants: 40,
    day: 'SAT',
    dayLabel: 'SAT 16 MAY',
  },
  {
    id: 'classical-dance-sat',
    name: 'Classical Dance',
    category: 'Dance',
    mainCategory: 'Non-Tech',
    date: '2026-05-16',
    timeSlot: '10:00 AM',
    endTime: '12:30 PM',
    venue: 'Main Auditorium',
    fillingFast: false,
    maxParticipants: 40,
    day: 'SAT',
    dayLabel: 'SAT 16 MAY',
  },
  {
    id: 'instrumental-sat',
    name: 'Instrumental Music',
    category: 'Music',
    mainCategory: 'Non-Tech',
    date: '2026-05-16',
    timeSlot: '02:00 PM',
    endTime: '04:00 PM',
    venue: 'Main Auditorium',
    fillingFast: false,
    maxParticipants: 25,
    day: 'SAT',
    dayLabel: 'SAT 16 MAY',
  },
  {
    id: 'talent-show-sat',
    name: 'Talent Show',
    category: 'Speaking',
    mainCategory: 'Non-Tech',
    date: '2026-05-16',
    timeSlot: '04:30 PM',
    endTime: '07:00 PM',
    venue: 'Main Auditorium',
    fillingFast: true,
    maxParticipants: 30,
    day: 'SAT',
    dayLabel: 'SAT 16 MAY',
  },
  {
    id: 'track-boys-sat',
    name: 'Track Events (Boys)',
    category: 'Athletics',
    mainCategory: 'Sports',
    date: '2026-05-16',
    timeSlot: '07:00 AM',
    endTime: '12:00 PM',
    venue: 'Athletic Track',
    fillingFast: false,
    maxParticipants: 50,
    day: 'SAT',
    dayLabel: 'SAT 16 MAY',
  },
  {
    id: 'volleyball-boys-sat',
    name: 'Volleyball (Boys)',
    category: 'Sports',
    mainCategory: 'Sports',
    date: '2026-05-16',
    timeSlot: '08:00 AM',
    endTime: '01:00 PM',
    venue: 'Sports Ground - Court A',
    fillingFast: false,
    maxParticipants: 24,
    day: 'SAT',
    dayLabel: 'SAT 16 MAY',
  },
  {
    id: 'mehendi-sat',
    name: 'Mehendi',
    category: 'Fun',
    mainCategory: 'Non-Tech',
    date: '2026-05-16',
    timeSlot: '10:00 AM',
    endTime: '12:00 PM',
    venue: 'Creative Arts Room',
    fillingFast: true,
    maxParticipants: 30,
    day: 'SAT',
    dayLabel: 'SAT 16 MAY',
  },
  {
    id: 'open-mic-sat',
    name: 'Open Mic (Poetry/Storytelling)',
    category: 'Speaking',
    mainCategory: 'Non-Tech',
    date: '2026-05-16',
    timeSlot: '12:00 PM',
    endTime: '02:00 PM',
    venue: 'Seminar Hall A',
    fillingFast: false,
    maxParticipants: 25,
    day: 'SAT',
    dayLabel: 'SAT 16 MAY',
  },
  {
    id: 'treasure-hunt-sat',
    name: 'Treasure Hunt',
    category: 'Fun',
    mainCategory: 'Non-Tech',
    date: '2026-05-16',
    timeSlot: '09:00 AM',
    endTime: '11:30 AM',
    venue: 'Campus Grounds',
    fillingFast: true,
    maxParticipants: 50,
    day: 'SAT',
    dayLabel: 'SAT 16 MAY',
  },
  {
    id: 'short-films-sat',
    name: 'Short Films',
    category: 'Fun',
    mainCategory: 'Non-Tech',
    date: '2026-05-16',
    timeSlot: '05:00 PM',
    endTime: '08:00 PM',
    venue: 'Main Auditorium',
    fillingFast: false,
    maxParticipants: 20,
    day: 'SAT',
    dayLabel: 'SAT 16 MAY',
  },
]