/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LiveScoresRouteImport } from './routes/live-scores'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CaptainsRouteImport } from './routes/captains'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as AdminLayoutSettingsRouteImport } from './routes/admin/_layout/settings'
import { Route as AdminLayoutParticipantsRouteImport } from './routes/admin/_layout/participants'
import { Route as AdminLayoutLeaderboardRouteImport } from './routes/admin/_layout/leaderboard'
import { Route as AdminLayoutHousesRouteImport } from './routes/admin/_layout/houses'
import { Route as AdminLayoutEventsRouteImport } from './routes/admin/_layout/events'
import { Route as AdminLayoutAnnouncementsRouteImport } from './routes/admin/_layout/announcements'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveScoresRoute = LiveScoresRouteImport.update({
  id: '/live-scores',
  path: '/live-scores',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainsRoute = CaptainsRouteImport.update({
  id: '/captains',
  path: '/captains',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutSettingsRoute = AdminLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutParticipantsRoute = AdminLayoutParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutLeaderboardRoute = AdminLayoutLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutHousesRoute = AdminLayoutHousesRouteImport.update({
  id: '/houses',
  path: '/houses',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutEventsRoute = AdminLayoutEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutAnnouncementsRoute =
  AdminLayoutAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AdminLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/captains': typeof CaptainsRoute
  '/events': typeof EventsRoute
  '/live-scores': typeof LiveScoresRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/announcements': typeof AdminLayoutAnnouncementsRoute
  '/admin/events': typeof AdminLayoutEventsRoute
  '/admin/houses': typeof AdminLayoutHousesRoute
  '/admin/leaderboard': typeof AdminLayoutLeaderboardRoute
  '/admin/participants': typeof AdminLayoutParticipantsRoute
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/admin/': typeof AdminLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/captains': typeof CaptainsRoute
  '/events': typeof EventsRoute
  '/live-scores': typeof LiveScoresRoute
  '/register': typeof RegisterRoute
  '/admin/announcements': typeof AdminLayoutAnnouncementsRoute
  '/admin/events': typeof AdminLayoutEventsRoute
  '/admin/houses': typeof AdminLayoutHousesRoute
  '/admin/leaderboard': typeof AdminLayoutLeaderboardRoute
  '/admin/participants': typeof AdminLayoutParticipantsRoute
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/admin': typeof AdminLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/captains': typeof CaptainsRoute
  '/events': typeof EventsRoute
  '/live-scores': typeof LiveScoresRoute
  '/register': typeof RegisterRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/_layout/announcements': typeof AdminLayoutAnnouncementsRoute
  '/admin/_layout/events': typeof AdminLayoutEventsRoute
  '/admin/_layout/houses': typeof AdminLayoutHousesRoute
  '/admin/_layout/leaderboard': typeof AdminLayoutLeaderboardRoute
  '/admin/_layout/participants': typeof AdminLayoutParticipantsRoute
  '/admin/_layout/settings': typeof AdminLayoutSettingsRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/captains'
    | '/events'
    | '/live-scores'
    | '/register'
    | '/admin'
    | '/admin/announcements'
    | '/admin/events'
    | '/admin/houses'
    | '/admin/leaderboard'
    | '/admin/participants'
    | '/admin/settings'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/captains'
    | '/events'
    | '/live-scores'
    | '/register'
    | '/admin/announcements'
    | '/admin/events'
    | '/admin/houses'
    | '/admin/leaderboard'
    | '/admin/participants'
    | '/admin/settings'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/captains'
    | '/events'
    | '/live-scores'
    | '/register'
    | '/admin/_layout'
    | '/admin/_layout/announcements'
    | '/admin/_layout/events'
    | '/admin/_layout/houses'
    | '/admin/_layout/leaderboard'
    | '/admin/_layout/participants'
    | '/admin/_layout/settings'
    | '/admin/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptainsRoute: typeof CaptainsRoute
  EventsRoute: typeof EventsRoute
  LiveScoresRoute: typeof LiveScoresRoute
  RegisterRoute: typeof RegisterRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-scores': {
      id: '/live-scores'
      path: '/live-scores'
      fullPath: '/live-scores'
      preLoaderRoute: typeof LiveScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captains': {
      id: '/captains'
      path: '/captains'
      fullPath: '/captains'
      preLoaderRoute: typeof CaptainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/settings': {
      id: '/admin/_layout/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminLayoutSettingsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/participants': {
      id: '/admin/_layout/participants'
      path: '/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminLayoutParticipantsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/leaderboard': {
      id: '/admin/_layout/leaderboard'
      path: '/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AdminLayoutLeaderboardRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/houses': {
      id: '/admin/_layout/houses'
      path: '/houses'
      fullPath: '/admin/houses'
      preLoaderRoute: typeof AdminLayoutHousesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/events': {
      id: '/admin/_layout/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminLayoutEventsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/announcements': {
      id: '/admin/_layout/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminLayoutAnnouncementsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
  }
}

interface AdminLayoutRouteChildren {
  AdminLayoutAnnouncementsRoute: typeof AdminLayoutAnnouncementsRoute
  AdminLayoutEventsRoute: typeof AdminLayoutEventsRoute
  AdminLayoutHousesRoute: typeof AdminLayoutHousesRoute
  AdminLayoutLeaderboardRoute: typeof AdminLayoutLeaderboardRoute
  AdminLayoutParticipantsRoute: typeof AdminLayoutParticipantsRoute
  AdminLayoutSettingsRoute: typeof AdminLayoutSettingsRoute
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutAnnouncementsRoute: AdminLayoutAnnouncementsRoute,
  AdminLayoutEventsRoute: AdminLayoutEventsRoute,
  AdminLayoutHousesRoute: AdminLayoutHousesRoute,
  AdminLayoutLeaderboardRoute: AdminLayoutLeaderboardRoute,
  AdminLayoutParticipantsRoute: AdminLayoutParticipantsRoute,
  AdminLayoutSettingsRoute: AdminLayoutSettingsRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptainsRoute: CaptainsRoute,
  EventsRoute: EventsRoute,
  LiveScoresRoute: LiveScoresRoute,
  RegisterRoute: RegisterRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
