/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as Wch1925LoginRouteImport } from './routes/wch1925/login'
import { Route as Wch1925LayoutRouteImport } from './routes/wch1925/_layout'
import { Route as EventsRegisterRouteImport } from './routes/events/register'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardMyScheduleRouteImport } from './routes/dashboard/my-schedule'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as Wch1925LayoutIndexRouteImport } from './routes/wch1925/_layout/index'
import { Route as Wch1925LayoutUserManagementRouteImport } from './routes/wch1925/_layout/user-management'
import { Route as Wch1925LayoutSettingsRouteImport } from './routes/wch1925/_layout/settings'
import { Route as Wch1925LayoutRulesRouteImport } from './routes/wch1925/_layout/rules'
import { Route as Wch1925LayoutRegistrationsRouteImport } from './routes/wch1925/_layout/registrations'
import { Route as Wch1925LayoutParticipantsRouteImport } from './routes/wch1925/_layout/participants'
import { Route as Wch1925LayoutLeaderboardRouteImport } from './routes/wch1925/_layout/leaderboard'
import { Route as Wch1925LayoutHousesRouteImport } from './routes/wch1925/_layout/houses'
import { Route as Wch1925LayoutEventsRouteImport } from './routes/wch1925/_layout/events'
import { Route as Wch1925LayoutDepartmentLeaderboardRouteImport } from './routes/wch1925/_layout/department-leaderboard'
import { Route as Wch1925LayoutDataEntryRouteImport } from './routes/wch1925/_layout/data-entry'
import { Route as Wch1925LayoutCheckinRouteImport } from './routes/wch1925/_layout/checkin'
import { Route as Wch1925LayoutAnnouncementsRouteImport } from './routes/wch1925/_layout/announcements'
import { Route as Wch1925LayoutCheckinNewRouteImport } from './routes/wch1925/_layout/checkin.new'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const Wch1925LoginRoute = Wch1925LoginRouteImport.update({
  id: '/wch1925/login',
  path: '/wch1925/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Wch1925LayoutRoute = Wch1925LayoutRouteImport.update({
  id: '/wch1925/_layout',
  path: '/wch1925',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRegisterRoute = EventsRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => EventsRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyScheduleRoute = DashboardMyScheduleRouteImport.update({
  id: '/my-schedule',
  path: '/my-schedule',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const Wch1925LayoutIndexRoute = Wch1925LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => Wch1925LayoutRoute,
} as any)
const Wch1925LayoutUserManagementRoute =
  Wch1925LayoutUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => Wch1925LayoutRoute,
  } as any)
const Wch1925LayoutSettingsRoute = Wch1925LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => Wch1925LayoutRoute,
} as any)
const Wch1925LayoutRulesRoute = Wch1925LayoutRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => Wch1925LayoutRoute,
} as any)
const Wch1925LayoutRegistrationsRoute =
  Wch1925LayoutRegistrationsRouteImport.update({
    id: '/registrations',
    path: '/registrations',
    getParentRoute: () => Wch1925LayoutRoute,
  } as any)
const Wch1925LayoutParticipantsRoute =
  Wch1925LayoutParticipantsRouteImport.update({
    id: '/participants',
    path: '/participants',
    getParentRoute: () => Wch1925LayoutRoute,
  } as any)
const Wch1925LayoutLeaderboardRoute =
  Wch1925LayoutLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => Wch1925LayoutRoute,
  } as any)
const Wch1925LayoutHousesRoute = Wch1925LayoutHousesRouteImport.update({
  id: '/houses',
  path: '/houses',
  getParentRoute: () => Wch1925LayoutRoute,
} as any)
const Wch1925LayoutEventsRoute = Wch1925LayoutEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => Wch1925LayoutRoute,
} as any)
const Wch1925LayoutDepartmentLeaderboardRoute =
  Wch1925LayoutDepartmentLeaderboardRouteImport.update({
    id: '/department-leaderboard',
    path: '/department-leaderboard',
    getParentRoute: () => Wch1925LayoutRoute,
  } as any)
const Wch1925LayoutDataEntryRoute = Wch1925LayoutDataEntryRouteImport.update({
  id: '/data-entry',
  path: '/data-entry',
  getParentRoute: () => Wch1925LayoutRoute,
} as any)
const Wch1925LayoutCheckinRoute = Wch1925LayoutCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => Wch1925LayoutRoute,
} as any)
const Wch1925LayoutAnnouncementsRoute =
  Wch1925LayoutAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => Wch1925LayoutRoute,
  } as any)
const Wch1925LayoutCheckinNewRoute = Wch1925LayoutCheckinNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => Wch1925LayoutCheckinRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/register': typeof RegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/my-schedule': typeof DashboardMyScheduleRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/events/register': typeof EventsRegisterRoute
  '/wch1925': typeof Wch1925LayoutRouteWithChildren
  '/wch1925/login': typeof Wch1925LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/wch1925/announcements': typeof Wch1925LayoutAnnouncementsRoute
  '/wch1925/checkin': typeof Wch1925LayoutCheckinRouteWithChildren
  '/wch1925/data-entry': typeof Wch1925LayoutDataEntryRoute
  '/wch1925/department-leaderboard': typeof Wch1925LayoutDepartmentLeaderboardRoute
  '/wch1925/events': typeof Wch1925LayoutEventsRoute
  '/wch1925/houses': typeof Wch1925LayoutHousesRoute
  '/wch1925/leaderboard': typeof Wch1925LayoutLeaderboardRoute
  '/wch1925/participants': typeof Wch1925LayoutParticipantsRoute
  '/wch1925/registrations': typeof Wch1925LayoutRegistrationsRoute
  '/wch1925/rules': typeof Wch1925LayoutRulesRoute
  '/wch1925/settings': typeof Wch1925LayoutSettingsRoute
  '/wch1925/user-management': typeof Wch1925LayoutUserManagementRoute
  '/wch1925/': typeof Wch1925LayoutIndexRoute
  '/wch1925/checkin/new': typeof Wch1925LayoutCheckinNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/my-schedule': typeof DashboardMyScheduleRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/events/register': typeof EventsRegisterRoute
  '/wch1925/login': typeof Wch1925LoginRoute
  '/dashboard': typeof DashboardIndexRoute
  '/events': typeof EventsIndexRoute
  '/wch1925/announcements': typeof Wch1925LayoutAnnouncementsRoute
  '/wch1925/checkin': typeof Wch1925LayoutCheckinRouteWithChildren
  '/wch1925/data-entry': typeof Wch1925LayoutDataEntryRoute
  '/wch1925/department-leaderboard': typeof Wch1925LayoutDepartmentLeaderboardRoute
  '/wch1925/events': typeof Wch1925LayoutEventsRoute
  '/wch1925/houses': typeof Wch1925LayoutHousesRoute
  '/wch1925/leaderboard': typeof Wch1925LayoutLeaderboardRoute
  '/wch1925/participants': typeof Wch1925LayoutParticipantsRoute
  '/wch1925/registrations': typeof Wch1925LayoutRegistrationsRoute
  '/wch1925/rules': typeof Wch1925LayoutRulesRoute
  '/wch1925/settings': typeof Wch1925LayoutSettingsRoute
  '/wch1925/user-management': typeof Wch1925LayoutUserManagementRoute
  '/wch1925': typeof Wch1925LayoutIndexRoute
  '/wch1925/checkin/new': typeof Wch1925LayoutCheckinNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/events': typeof EventsRouteWithChildren
  '/register': typeof RegisterRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/my-schedule': typeof DashboardMyScheduleRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/events/register': typeof EventsRegisterRoute
  '/wch1925/_layout': typeof Wch1925LayoutRouteWithChildren
  '/wch1925/login': typeof Wch1925LoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/wch1925/_layout/announcements': typeof Wch1925LayoutAnnouncementsRoute
  '/wch1925/_layout/checkin': typeof Wch1925LayoutCheckinRouteWithChildren
  '/wch1925/_layout/data-entry': typeof Wch1925LayoutDataEntryRoute
  '/wch1925/_layout/department-leaderboard': typeof Wch1925LayoutDepartmentLeaderboardRoute
  '/wch1925/_layout/events': typeof Wch1925LayoutEventsRoute
  '/wch1925/_layout/houses': typeof Wch1925LayoutHousesRoute
  '/wch1925/_layout/leaderboard': typeof Wch1925LayoutLeaderboardRoute
  '/wch1925/_layout/participants': typeof Wch1925LayoutParticipantsRoute
  '/wch1925/_layout/registrations': typeof Wch1925LayoutRegistrationsRoute
  '/wch1925/_layout/rules': typeof Wch1925LayoutRulesRoute
  '/wch1925/_layout/settings': typeof Wch1925LayoutSettingsRoute
  '/wch1925/_layout/user-management': typeof Wch1925LayoutUserManagementRoute
  '/wch1925/_layout/': typeof Wch1925LayoutIndexRoute
  '/wch1925/_layout/checkin/new': typeof Wch1925LayoutCheckinNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/events'
    | '/register'
    | '/auth/callback'
    | '/dashboard/my-schedule'
    | '/dashboard/profile'
    | '/events/register'
    | '/wch1925'
    | '/wch1925/login'
    | '/dashboard/'
    | '/events/'
    | '/wch1925/announcements'
    | '/wch1925/checkin'
    | '/wch1925/data-entry'
    | '/wch1925/department-leaderboard'
    | '/wch1925/events'
    | '/wch1925/houses'
    | '/wch1925/leaderboard'
    | '/wch1925/participants'
    | '/wch1925/registrations'
    | '/wch1925/rules'
    | '/wch1925/settings'
    | '/wch1925/user-management'
    | '/wch1925/'
    | '/wch1925/checkin/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/auth/callback'
    | '/dashboard/my-schedule'
    | '/dashboard/profile'
    | '/events/register'
    | '/wch1925/login'
    | '/dashboard'
    | '/events'
    | '/wch1925/announcements'
    | '/wch1925/checkin'
    | '/wch1925/data-entry'
    | '/wch1925/department-leaderboard'
    | '/wch1925/events'
    | '/wch1925/houses'
    | '/wch1925/leaderboard'
    | '/wch1925/participants'
    | '/wch1925/registrations'
    | '/wch1925/rules'
    | '/wch1925/settings'
    | '/wch1925/user-management'
    | '/wch1925'
    | '/wch1925/checkin/new'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/events'
    | '/register'
    | '/auth/callback'
    | '/dashboard/my-schedule'
    | '/dashboard/profile'
    | '/events/register'
    | '/wch1925/_layout'
    | '/wch1925/login'
    | '/dashboard/'
    | '/events/'
    | '/wch1925/_layout/announcements'
    | '/wch1925/_layout/checkin'
    | '/wch1925/_layout/data-entry'
    | '/wch1925/_layout/department-leaderboard'
    | '/wch1925/_layout/events'
    | '/wch1925/_layout/houses'
    | '/wch1925/_layout/leaderboard'
    | '/wch1925/_layout/participants'
    | '/wch1925/_layout/registrations'
    | '/wch1925/_layout/rules'
    | '/wch1925/_layout/settings'
    | '/wch1925/_layout/user-management'
    | '/wch1925/_layout/'
    | '/wch1925/_layout/checkin/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EventsRoute: typeof EventsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  Wch1925LayoutRoute: typeof Wch1925LayoutRouteWithChildren
  Wch1925LoginRoute: typeof Wch1925LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/wch1925/login': {
      id: '/wch1925/login'
      path: '/wch1925/login'
      fullPath: '/wch1925/login'
      preLoaderRoute: typeof Wch1925LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wch1925/_layout': {
      id: '/wch1925/_layout'
      path: '/wch1925'
      fullPath: '/wch1925'
      preLoaderRoute: typeof Wch1925LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/register': {
      id: '/events/register'
      path: '/register'
      fullPath: '/events/register'
      preLoaderRoute: typeof EventsRegisterRouteImport
      parentRoute: typeof EventsRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-schedule': {
      id: '/dashboard/my-schedule'
      path: '/my-schedule'
      fullPath: '/dashboard/my-schedule'
      preLoaderRoute: typeof DashboardMyScheduleRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wch1925/_layout/': {
      id: '/wch1925/_layout/'
      path: '/'
      fullPath: '/wch1925/'
      preLoaderRoute: typeof Wch1925LayoutIndexRouteImport
      parentRoute: typeof Wch1925LayoutRoute
    }
    '/wch1925/_layout/user-management': {
      id: '/wch1925/_layout/user-management'
      path: '/user-management'
      fullPath: '/wch1925/user-management'
      preLoaderRoute: typeof Wch1925LayoutUserManagementRouteImport
      parentRoute: typeof Wch1925LayoutRoute
    }
    '/wch1925/_layout/settings': {
      id: '/wch1925/_layout/settings'
      path: '/settings'
      fullPath: '/wch1925/settings'
      preLoaderRoute: typeof Wch1925LayoutSettingsRouteImport
      parentRoute: typeof Wch1925LayoutRoute
    }
    '/wch1925/_layout/rules': {
      id: '/wch1925/_layout/rules'
      path: '/rules'
      fullPath: '/wch1925/rules'
      preLoaderRoute: typeof Wch1925LayoutRulesRouteImport
      parentRoute: typeof Wch1925LayoutRoute
    }
    '/wch1925/_layout/registrations': {
      id: '/wch1925/_layout/registrations'
      path: '/registrations'
      fullPath: '/wch1925/registrations'
      preLoaderRoute: typeof Wch1925LayoutRegistrationsRouteImport
      parentRoute: typeof Wch1925LayoutRoute
    }
    '/wch1925/_layout/participants': {
      id: '/wch1925/_layout/participants'
      path: '/participants'
      fullPath: '/wch1925/participants'
      preLoaderRoute: typeof Wch1925LayoutParticipantsRouteImport
      parentRoute: typeof Wch1925LayoutRoute
    }
    '/wch1925/_layout/leaderboard': {
      id: '/wch1925/_layout/leaderboard'
      path: '/leaderboard'
      fullPath: '/wch1925/leaderboard'
      preLoaderRoute: typeof Wch1925LayoutLeaderboardRouteImport
      parentRoute: typeof Wch1925LayoutRoute
    }
    '/wch1925/_layout/houses': {
      id: '/wch1925/_layout/houses'
      path: '/houses'
      fullPath: '/wch1925/houses'
      preLoaderRoute: typeof Wch1925LayoutHousesRouteImport
      parentRoute: typeof Wch1925LayoutRoute
    }
    '/wch1925/_layout/events': {
      id: '/wch1925/_layout/events'
      path: '/events'
      fullPath: '/wch1925/events'
      preLoaderRoute: typeof Wch1925LayoutEventsRouteImport
      parentRoute: typeof Wch1925LayoutRoute
    }
    '/wch1925/_layout/department-leaderboard': {
      id: '/wch1925/_layout/department-leaderboard'
      path: '/department-leaderboard'
      fullPath: '/wch1925/department-leaderboard'
      preLoaderRoute: typeof Wch1925LayoutDepartmentLeaderboardRouteImport
      parentRoute: typeof Wch1925LayoutRoute
    }
    '/wch1925/_layout/data-entry': {
      id: '/wch1925/_layout/data-entry'
      path: '/data-entry'
      fullPath: '/wch1925/data-entry'
      preLoaderRoute: typeof Wch1925LayoutDataEntryRouteImport
      parentRoute: typeof Wch1925LayoutRoute
    }
    '/wch1925/_layout/checkin': {
      id: '/wch1925/_layout/checkin'
      path: '/checkin'
      fullPath: '/wch1925/checkin'
      preLoaderRoute: typeof Wch1925LayoutCheckinRouteImport
      parentRoute: typeof Wch1925LayoutRoute
    }
    '/wch1925/_layout/announcements': {
      id: '/wch1925/_layout/announcements'
      path: '/announcements'
      fullPath: '/wch1925/announcements'
      preLoaderRoute: typeof Wch1925LayoutAnnouncementsRouteImport
      parentRoute: typeof Wch1925LayoutRoute
    }
    '/wch1925/_layout/checkin/new': {
      id: '/wch1925/_layout/checkin/new'
      path: '/new'
      fullPath: '/wch1925/checkin/new'
      preLoaderRoute: typeof Wch1925LayoutCheckinNewRouteImport
      parentRoute: typeof Wch1925LayoutCheckinRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardMyScheduleRoute: typeof DashboardMyScheduleRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardMyScheduleRoute: DashboardMyScheduleRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface EventsRouteChildren {
  EventsRegisterRoute: typeof EventsRegisterRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsRegisterRoute: EventsRegisterRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface Wch1925LayoutCheckinRouteChildren {
  Wch1925LayoutCheckinNewRoute: typeof Wch1925LayoutCheckinNewRoute
}

const Wch1925LayoutCheckinRouteChildren: Wch1925LayoutCheckinRouteChildren = {
  Wch1925LayoutCheckinNewRoute: Wch1925LayoutCheckinNewRoute,
}

const Wch1925LayoutCheckinRouteWithChildren =
  Wch1925LayoutCheckinRoute._addFileChildren(Wch1925LayoutCheckinRouteChildren)

interface Wch1925LayoutRouteChildren {
  Wch1925LayoutAnnouncementsRoute: typeof Wch1925LayoutAnnouncementsRoute
  Wch1925LayoutCheckinRoute: typeof Wch1925LayoutCheckinRouteWithChildren
  Wch1925LayoutDataEntryRoute: typeof Wch1925LayoutDataEntryRoute
  Wch1925LayoutDepartmentLeaderboardRoute: typeof Wch1925LayoutDepartmentLeaderboardRoute
  Wch1925LayoutEventsRoute: typeof Wch1925LayoutEventsRoute
  Wch1925LayoutHousesRoute: typeof Wch1925LayoutHousesRoute
  Wch1925LayoutLeaderboardRoute: typeof Wch1925LayoutLeaderboardRoute
  Wch1925LayoutParticipantsRoute: typeof Wch1925LayoutParticipantsRoute
  Wch1925LayoutRegistrationsRoute: typeof Wch1925LayoutRegistrationsRoute
  Wch1925LayoutRulesRoute: typeof Wch1925LayoutRulesRoute
  Wch1925LayoutSettingsRoute: typeof Wch1925LayoutSettingsRoute
  Wch1925LayoutUserManagementRoute: typeof Wch1925LayoutUserManagementRoute
  Wch1925LayoutIndexRoute: typeof Wch1925LayoutIndexRoute
}

const Wch1925LayoutRouteChildren: Wch1925LayoutRouteChildren = {
  Wch1925LayoutAnnouncementsRoute: Wch1925LayoutAnnouncementsRoute,
  Wch1925LayoutCheckinRoute: Wch1925LayoutCheckinRouteWithChildren,
  Wch1925LayoutDataEntryRoute: Wch1925LayoutDataEntryRoute,
  Wch1925LayoutDepartmentLeaderboardRoute:
    Wch1925LayoutDepartmentLeaderboardRoute,
  Wch1925LayoutEventsRoute: Wch1925LayoutEventsRoute,
  Wch1925LayoutHousesRoute: Wch1925LayoutHousesRoute,
  Wch1925LayoutLeaderboardRoute: Wch1925LayoutLeaderboardRoute,
  Wch1925LayoutParticipantsRoute: Wch1925LayoutParticipantsRoute,
  Wch1925LayoutRegistrationsRoute: Wch1925LayoutRegistrationsRoute,
  Wch1925LayoutRulesRoute: Wch1925LayoutRulesRoute,
  Wch1925LayoutSettingsRoute: Wch1925LayoutSettingsRoute,
  Wch1925LayoutUserManagementRoute: Wch1925LayoutUserManagementRoute,
  Wch1925LayoutIndexRoute: Wch1925LayoutIndexRoute,
}

const Wch1925LayoutRouteWithChildren = Wch1925LayoutRoute._addFileChildren(
  Wch1925LayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EventsRoute: EventsRouteWithChildren,
  RegisterRoute: RegisterRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  Wch1925LayoutRoute: Wch1925LayoutRouteWithChildren,
  Wch1925LoginRoute: Wch1925LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
