/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MyScheduleRouteImport } from './routes/my-schedule'
import { Route as LiveScoresRouteImport } from './routes/live-scores'
import { Route as LiveRouteImport } from './routes/live'
import { Route as EventsRouteImport } from './routes/events'
import { Route as CaptainsRouteImport } from './routes/captains'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UserIndexRouteImport } from './routes/user/index'
import { Route as UserProfileRouteImport } from './routes/user/profile'
import { Route as UserMyScheduleRouteImport } from './routes/user/my-schedule'
import { Route as UserLayoutRouteImport } from './routes/user/_layout'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminLayoutIndexRouteImport } from './routes/admin/_layout/index'
import { Route as AdminLayoutUserManagementRouteImport } from './routes/admin/_layout/user-management'
import { Route as AdminLayoutSettingsRouteImport } from './routes/admin/_layout/settings'
import { Route as AdminLayoutRulesRouteImport } from './routes/admin/_layout/rules'
import { Route as AdminLayoutRegistrationsRouteImport } from './routes/admin/_layout/registrations'
import { Route as AdminLayoutParticipantsRouteImport } from './routes/admin/_layout/participants'
import { Route as AdminLayoutLeaderboardRouteImport } from './routes/admin/_layout/leaderboard'
import { Route as AdminLayoutHousesRouteImport } from './routes/admin/_layout/houses'
import { Route as AdminLayoutEventsRouteImport } from './routes/admin/_layout/events'
import { Route as AdminLayoutDataEntryRouteImport } from './routes/admin/_layout/data-entry'
import { Route as AdminLayoutCheckinRouteImport } from './routes/admin/_layout/checkin'
import { Route as AdminLayoutAnnouncementsRouteImport } from './routes/admin/_layout/announcements'
import { Route as AdminLayoutCheckinNewRouteImport } from './routes/admin/_layout/checkin.new'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyScheduleRoute = MyScheduleRouteImport.update({
  id: '/my-schedule',
  path: '/my-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveScoresRoute = LiveScoresRouteImport.update({
  id: '/live-scores',
  path: '/live-scores',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptainsRoute = CaptainsRouteImport.update({
  id: '/captains',
  path: '/captains',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/user/profile',
  path: '/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const UserMyScheduleRoute = UserMyScheduleRouteImport.update({
  id: '/user/my-schedule',
  path: '/user/my-schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const UserLayoutRoute = UserLayoutRouteImport.update({
  id: '/user/_layout',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutIndexRoute = AdminLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutUserManagementRoute =
  AdminLayoutUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutSettingsRoute = AdminLayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutRulesRoute = AdminLayoutRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutRegistrationsRoute =
  AdminLayoutRegistrationsRouteImport.update({
    id: '/registrations',
    path: '/registrations',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutParticipantsRoute = AdminLayoutParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutLeaderboardRoute = AdminLayoutLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutHousesRoute = AdminLayoutHousesRouteImport.update({
  id: '/houses',
  path: '/houses',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutEventsRoute = AdminLayoutEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutDataEntryRoute = AdminLayoutDataEntryRouteImport.update({
  id: '/data-entry',
  path: '/data-entry',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutCheckinRoute = AdminLayoutCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutAnnouncementsRoute =
  AdminLayoutAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AdminLayoutRoute,
  } as any)
const AdminLayoutCheckinNewRoute = AdminLayoutCheckinNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminLayoutCheckinRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/captains': typeof CaptainsRoute
  '/events': typeof EventsRoute
  '/live': typeof LiveRoute
  '/live-scores': typeof LiveScoresRoute
  '/my-schedule': typeof MyScheduleRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/user': typeof UserLayoutRoute
  '/user/my-schedule': typeof UserMyScheduleRoute
  '/user/profile': typeof UserProfileRoute
  '/user/': typeof UserIndexRoute
  '/admin/announcements': typeof AdminLayoutAnnouncementsRoute
  '/admin/checkin': typeof AdminLayoutCheckinRouteWithChildren
  '/admin/data-entry': typeof AdminLayoutDataEntryRoute
  '/admin/events': typeof AdminLayoutEventsRoute
  '/admin/houses': typeof AdminLayoutHousesRoute
  '/admin/leaderboard': typeof AdminLayoutLeaderboardRoute
  '/admin/participants': typeof AdminLayoutParticipantsRoute
  '/admin/registrations': typeof AdminLayoutRegistrationsRoute
  '/admin/rules': typeof AdminLayoutRulesRoute
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/admin/user-management': typeof AdminLayoutUserManagementRoute
  '/admin/': typeof AdminLayoutIndexRoute
  '/admin/checkin/new': typeof AdminLayoutCheckinNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/captains': typeof CaptainsRoute
  '/events': typeof EventsRoute
  '/live': typeof LiveRoute
  '/live-scores': typeof LiveScoresRoute
  '/my-schedule': typeof MyScheduleRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/login': typeof AdminLoginRoute
  '/user': typeof UserIndexRoute
  '/user/my-schedule': typeof UserMyScheduleRoute
  '/user/profile': typeof UserProfileRoute
  '/admin/announcements': typeof AdminLayoutAnnouncementsRoute
  '/admin/checkin': typeof AdminLayoutCheckinRouteWithChildren
  '/admin/data-entry': typeof AdminLayoutDataEntryRoute
  '/admin/events': typeof AdminLayoutEventsRoute
  '/admin/houses': typeof AdminLayoutHousesRoute
  '/admin/leaderboard': typeof AdminLayoutLeaderboardRoute
  '/admin/participants': typeof AdminLayoutParticipantsRoute
  '/admin/registrations': typeof AdminLayoutRegistrationsRoute
  '/admin/rules': typeof AdminLayoutRulesRoute
  '/admin/settings': typeof AdminLayoutSettingsRoute
  '/admin/user-management': typeof AdminLayoutUserManagementRoute
  '/admin': typeof AdminLayoutIndexRoute
  '/admin/checkin/new': typeof AdminLayoutCheckinNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/captains': typeof CaptainsRoute
  '/events': typeof EventsRoute
  '/live': typeof LiveRoute
  '/live-scores': typeof LiveScoresRoute
  '/my-schedule': typeof MyScheduleRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/user/_layout': typeof UserLayoutRoute
  '/user/my-schedule': typeof UserMyScheduleRoute
  '/user/profile': typeof UserProfileRoute
  '/user/': typeof UserIndexRoute
  '/admin/_layout/announcements': typeof AdminLayoutAnnouncementsRoute
  '/admin/_layout/checkin': typeof AdminLayoutCheckinRouteWithChildren
  '/admin/_layout/data-entry': typeof AdminLayoutDataEntryRoute
  '/admin/_layout/events': typeof AdminLayoutEventsRoute
  '/admin/_layout/houses': typeof AdminLayoutHousesRoute
  '/admin/_layout/leaderboard': typeof AdminLayoutLeaderboardRoute
  '/admin/_layout/participants': typeof AdminLayoutParticipantsRoute
  '/admin/_layout/registrations': typeof AdminLayoutRegistrationsRoute
  '/admin/_layout/rules': typeof AdminLayoutRulesRoute
  '/admin/_layout/settings': typeof AdminLayoutSettingsRoute
  '/admin/_layout/user-management': typeof AdminLayoutUserManagementRoute
  '/admin/_layout/': typeof AdminLayoutIndexRoute
  '/admin/_layout/checkin/new': typeof AdminLayoutCheckinNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/captains'
    | '/events'
    | '/live'
    | '/live-scores'
    | '/my-schedule'
    | '/profile'
    | '/register'
    | '/admin'
    | '/admin/login'
    | '/user'
    | '/user/my-schedule'
    | '/user/profile'
    | '/user/'
    | '/admin/announcements'
    | '/admin/checkin'
    | '/admin/data-entry'
    | '/admin/events'
    | '/admin/houses'
    | '/admin/leaderboard'
    | '/admin/participants'
    | '/admin/registrations'
    | '/admin/rules'
    | '/admin/settings'
    | '/admin/user-management'
    | '/admin/'
    | '/admin/checkin/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/captains'
    | '/events'
    | '/live'
    | '/live-scores'
    | '/my-schedule'
    | '/profile'
    | '/register'
    | '/admin/login'
    | '/user'
    | '/user/my-schedule'
    | '/user/profile'
    | '/admin/announcements'
    | '/admin/checkin'
    | '/admin/data-entry'
    | '/admin/events'
    | '/admin/houses'
    | '/admin/leaderboard'
    | '/admin/participants'
    | '/admin/registrations'
    | '/admin/rules'
    | '/admin/settings'
    | '/admin/user-management'
    | '/admin'
    | '/admin/checkin/new'
  id:
    | '__root__'
    | '/'
    | '/captains'
    | '/events'
    | '/live'
    | '/live-scores'
    | '/my-schedule'
    | '/profile'
    | '/register'
    | '/admin/_layout'
    | '/admin/login'
    | '/user/_layout'
    | '/user/my-schedule'
    | '/user/profile'
    | '/user/'
    | '/admin/_layout/announcements'
    | '/admin/_layout/checkin'
    | '/admin/_layout/data-entry'
    | '/admin/_layout/events'
    | '/admin/_layout/houses'
    | '/admin/_layout/leaderboard'
    | '/admin/_layout/participants'
    | '/admin/_layout/registrations'
    | '/admin/_layout/rules'
    | '/admin/_layout/settings'
    | '/admin/_layout/user-management'
    | '/admin/_layout/'
    | '/admin/_layout/checkin/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaptainsRoute: typeof CaptainsRoute
  EventsRoute: typeof EventsRoute
  LiveRoute: typeof LiveRoute
  LiveScoresRoute: typeof LiveScoresRoute
  MyScheduleRoute: typeof MyScheduleRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  UserLayoutRoute: typeof UserLayoutRoute
  UserMyScheduleRoute: typeof UserMyScheduleRoute
  UserProfileRoute: typeof UserProfileRoute
  UserIndexRoute: typeof UserIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-schedule': {
      id: '/my-schedule'
      path: '/my-schedule'
      fullPath: '/my-schedule'
      preLoaderRoute: typeof MyScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-scores': {
      id: '/live-scores'
      path: '/live-scores'
      fullPath: '/live-scores'
      preLoaderRoute: typeof LiveScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/captains': {
      id: '/captains'
      path: '/captains'
      fullPath: '/captains'
      preLoaderRoute: typeof CaptainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/': {
      id: '/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/user/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/my-schedule': {
      id: '/user/my-schedule'
      path: '/user/my-schedule'
      fullPath: '/user/my-schedule'
      preLoaderRoute: typeof UserMyScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/_layout': {
      id: '/user/_layout'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout/': {
      id: '/admin/_layout/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminLayoutIndexRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/user-management': {
      id: '/admin/_layout/user-management'
      path: '/user-management'
      fullPath: '/admin/user-management'
      preLoaderRoute: typeof AdminLayoutUserManagementRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/settings': {
      id: '/admin/_layout/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminLayoutSettingsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/rules': {
      id: '/admin/_layout/rules'
      path: '/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AdminLayoutRulesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/registrations': {
      id: '/admin/_layout/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AdminLayoutRegistrationsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/participants': {
      id: '/admin/_layout/participants'
      path: '/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminLayoutParticipantsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/leaderboard': {
      id: '/admin/_layout/leaderboard'
      path: '/leaderboard'
      fullPath: '/admin/leaderboard'
      preLoaderRoute: typeof AdminLayoutLeaderboardRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/houses': {
      id: '/admin/_layout/houses'
      path: '/houses'
      fullPath: '/admin/houses'
      preLoaderRoute: typeof AdminLayoutHousesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/events': {
      id: '/admin/_layout/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminLayoutEventsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/data-entry': {
      id: '/admin/_layout/data-entry'
      path: '/data-entry'
      fullPath: '/admin/data-entry'
      preLoaderRoute: typeof AdminLayoutDataEntryRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/checkin': {
      id: '/admin/_layout/checkin'
      path: '/checkin'
      fullPath: '/admin/checkin'
      preLoaderRoute: typeof AdminLayoutCheckinRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/announcements': {
      id: '/admin/_layout/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminLayoutAnnouncementsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/checkin/new': {
      id: '/admin/_layout/checkin/new'
      path: '/new'
      fullPath: '/admin/checkin/new'
      preLoaderRoute: typeof AdminLayoutCheckinNewRouteImport
      parentRoute: typeof AdminLayoutCheckinRoute
    }
  }
}

interface AdminLayoutCheckinRouteChildren {
  AdminLayoutCheckinNewRoute: typeof AdminLayoutCheckinNewRoute
}

const AdminLayoutCheckinRouteChildren: AdminLayoutCheckinRouteChildren = {
  AdminLayoutCheckinNewRoute: AdminLayoutCheckinNewRoute,
}

const AdminLayoutCheckinRouteWithChildren =
  AdminLayoutCheckinRoute._addFileChildren(AdminLayoutCheckinRouteChildren)

interface AdminLayoutRouteChildren {
  AdminLayoutAnnouncementsRoute: typeof AdminLayoutAnnouncementsRoute
  AdminLayoutCheckinRoute: typeof AdminLayoutCheckinRouteWithChildren
  AdminLayoutDataEntryRoute: typeof AdminLayoutDataEntryRoute
  AdminLayoutEventsRoute: typeof AdminLayoutEventsRoute
  AdminLayoutHousesRoute: typeof AdminLayoutHousesRoute
  AdminLayoutLeaderboardRoute: typeof AdminLayoutLeaderboardRoute
  AdminLayoutParticipantsRoute: typeof AdminLayoutParticipantsRoute
  AdminLayoutRegistrationsRoute: typeof AdminLayoutRegistrationsRoute
  AdminLayoutRulesRoute: typeof AdminLayoutRulesRoute
  AdminLayoutSettingsRoute: typeof AdminLayoutSettingsRoute
  AdminLayoutUserManagementRoute: typeof AdminLayoutUserManagementRoute
  AdminLayoutIndexRoute: typeof AdminLayoutIndexRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutAnnouncementsRoute: AdminLayoutAnnouncementsRoute,
  AdminLayoutCheckinRoute: AdminLayoutCheckinRouteWithChildren,
  AdminLayoutDataEntryRoute: AdminLayoutDataEntryRoute,
  AdminLayoutEventsRoute: AdminLayoutEventsRoute,
  AdminLayoutHousesRoute: AdminLayoutHousesRoute,
  AdminLayoutLeaderboardRoute: AdminLayoutLeaderboardRoute,
  AdminLayoutParticipantsRoute: AdminLayoutParticipantsRoute,
  AdminLayoutRegistrationsRoute: AdminLayoutRegistrationsRoute,
  AdminLayoutRulesRoute: AdminLayoutRulesRoute,
  AdminLayoutSettingsRoute: AdminLayoutSettingsRoute,
  AdminLayoutUserManagementRoute: AdminLayoutUserManagementRoute,
  AdminLayoutIndexRoute: AdminLayoutIndexRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaptainsRoute: CaptainsRoute,
  EventsRoute: EventsRoute,
  LiveRoute: LiveRoute,
  LiveScoresRoute: LiveScoresRoute,
  MyScheduleRoute: MyScheduleRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  UserLayoutRoute: UserLayoutRoute,
  UserMyScheduleRoute: UserMyScheduleRoute,
  UserProfileRoute: UserProfileRoute,
  UserIndexRoute: UserIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
